{{- if and .Values.paperclip.postgres.url (not .Values.paperclip.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperclip.fullname" . }}-db
  labels:
    {{- include "paperclip.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.paperclip.postgres.url | quote }}
{{- end }}
---
{{- if and .Values.paperclip.auth.secret (not .Values.paperclip.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperclip.fullname" . }}-auth
  labels:
    {{- include "paperclip.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.paperclip.auth.secret | quote }}
{{- end }}
